"""
build_us_personas.py — Build the US persona database from Tianyi-Lab/Personas.

Source: Tianyi-Lab/Personas (arXiv:2503.16527, NeurIPS 2025)
HuggingFace: https://huggingface.co/datasets/Tianyi-Lab/Personas
License: Publicly available (no gating)

The dataset has ~48,000 US personas across 48 states. Each row contains three
tiers generated by 6 LLMs. We use the Llama-3.1-70B-Instruct tier (highest quality)
for all text fields, with meta_persona as ground truth for Census-grounded demographics.

Three tiers per row:
  1. meta_persona (dict): AGE (range), SEX, RACE, STATE — Census joint distribution
  2. objective_table_persona (JSON string): 20+ structured demographic fields
  3. subjective_table_persona (JSON string): personality, political views, religion,
     BIG_FIVE_SCORES, IDEOLOGY, LIFESTYLE, DEFINING_QUIRKS, MANNERISMS, PERSONAL_TIME
  4. descriptive_persona (str): 1,000–5,000 char narrative biography

Outputs:
  - simulate/personas/us_personas.json — 10,000 stratified personas
  - simulate/personas/us_personas_full.json — full uncapped adult-US database
Fields compatible with format_personalization() [TAG] system in simulate/agent.py.

Run:
    pip install datasets
    python3 -m simulate.personas.build_us_personas
    python3 -m simulate.personas.build_us_personas --full
"""

import argparse
import json
import os
import re
import sys

# ---------------------------------------------------------------------------
# Census target distributions for stratification (2023 ACS / Pew)
# ---------------------------------------------------------------------------

# Race targets (meta_persona RACE field values from Census)
RACE_TARGETS = {
    "White": 0.595,
    "Hispanic": 0.190,
    "Black": 0.130,
    "Asian": 0.060,
    "Other": 0.025,  # AIAN, NHPI, Two or more races
}

# Age group targets (18+, US Census 2023)
AGE_TARGETS = {
    "18-29": 0.220,
    "30-44": 0.250,
    "45-59": 0.240,
    "60+":   0.290,
}

# Sex targets
SEX_TARGETS = {
    "Female": 0.507,
    "Male":   0.493,
}

# US region → states mapping (for region-balanced sampling)
REGION_STATES = {
    "Northeast": ["CT", "ME", "MA", "NH", "NJ", "NY", "PA", "RI", "VT"],
    "Midwest":   ["IL", "IN", "IA", "KS", "MI", "MN", "MO", "NE", "ND", "OH", "SD", "WI"],
    "South":     ["AL", "AR", "DC", "DE", "FL", "GA", "KY", "LA", "MD", "MS", "NC", "OK", "SC", "TN", "TX", "VA", "WV"],
    "West":      ["AK", "AZ", "CA", "CO", "HI", "ID", "MT", "NV", "NM", "OR", "UT", "WA", "WY"],
}
STATE_TO_REGION = {s: r for r, states in REGION_STATES.items() for s in states}

# Model to use for all text tiers
MODEL = "Llama-3.1-70B-Instruct"

# Target number of personas
TARGET_N = 10_000
DEFAULT_OUTPUT_FILENAME = "us_personas.json"
FULL_OUTPUT_FILENAME = "us_personas_full.json"

# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def safe_parse_json(raw):
    """Parse a JSON string; return empty dict on failure."""
    if isinstance(raw, dict):
        return raw
    if not isinstance(raw, str):
        return {}
    raw = raw.strip()
    # Strip surrounding quotes if double-encoded
    if raw.startswith('"') and raw.endswith('"'):
        try:
            raw = json.loads(raw)
        except Exception:
            pass
    try:
        return json.loads(raw)
    except Exception:
        return {}


def map_age_range(age_str):
    """Convert Census age range string to integer midpoint."""
    if not age_str:
        return None
    # Try direct int
    try:
        return int(str(age_str))
    except (ValueError, TypeError):
        pass
    # Try range like "75-84"
    m = re.match(r'(\d+)-(\d+)', str(age_str))
    if m:
        lo, hi = int(m.group(1)), int(m.group(2))
        return (lo + hi) // 2
    # Try "85+" or "65+"
    m = re.match(r'(\d+)\+', str(age_str))
    if m:
        return int(m.group(1)) + 5
    return None


def get_age_bucket(age):
    if age is None:
        return None
    if age < 18:
        return None
    if age < 30:
        return "18-29"
    if age < 45:
        return "30-44"
    if age < 60:
        return "45-59"
    return "60+"


def normalize_race(race_str):
    """Map Census race/ethnicity labels to clean standard values."""
    if not race_str:
        return "Other"
    r = str(race_str).strip()
    mapping = {
        "White": "White",
        "White alone": "White",
        "Black": "Black",
        "Black or African American": "Black",
        "Black alone": "Black",
        "Hispanic": "Hispanic",
        "Hispanic or Latino": "Hispanic",
        "Asian": "Asian",
        "Asian alone": "Asian",
        "American Indian": "Other",
        "Alaska Native": "Other",
        "Native Hawaiian": "Other",
        "Pacific Islander": "Other",
        "Two or More Races": "Other",
        "Some Other Race": "Other",
        "Other": "Other",
    }
    for key, val in mapping.items():
        if r.lower() == key.lower() or r.lower().startswith(key.lower()):
            return val
    # Check for Hispanic via regex
    if re.search(r'hispanic|latino', r, re.IGNORECASE):
        return "Hispanic"
    return r  # Return as-is if no match


def normalize_sex(sex_str):
    if not sex_str:
        return "Unknown"
    s = str(sex_str).strip().lower()
    if s in ("female", "f", "woman"):
        return "Woman"
    if s in ("male", "m", "man"):
        return "Man"
    return str(sex_str).strip()


def extract_name_from_bio(bio_str):
    """Try to extract the persona's name from the narrative bio."""
    if not bio_str:
        return None
    # Common patterns: "Meet Sarah Johnson," or "John Smith is a 45-year-old"
    patterns = [
        r'^(?:Meet\s+)?([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})[,\s]',
        r'^(?:Name:\s*\*\*?)([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})(?:\*\*?)?',
        r'\*\*Name:\*\*\s*([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,3})',
    ]
    for pat in patterns:
        m = re.search(pat, bio_str.strip())
        if m:
            name = m.group(1).strip()
            # Filter out generic openers
            if name.lower() not in ("meet", "this", "the", "a", "an"):
                return name
    return None


def parse_big_five(bf_val):
    """Parse BIG_FIVE_SCORES field to a readable string."""
    if not bf_val:
        return None
    if isinstance(bf_val, dict):
        parts = []
        for trait, score in bf_val.items():
            trait_short = trait.replace("_", " ").replace("Big Five: ", "").strip()
            parts.append(f"{trait_short}: {score}")
        return "; ".join(parts)
    return str(bf_val)[:300]


def normalize_persona(row):
    """
    Parse a Tianyi-Lab/Personas row into a normalized persona dict.
    Returns None if the persona is under 18 or missing critical fields.
    """
    # --- Census-grounded meta fields ---
    meta = row.get("meta_persona", {})
    if isinstance(meta, str):
        meta = safe_parse_json(meta)

    raw_age = meta.get("AGE") or meta.get("Age")
    raw_sex = meta.get("SEX") or meta.get("Sex")
    raw_race = meta.get("RACE") or meta.get("Race")
    raw_state = str(meta.get("STATE") or meta.get("State") or row.get("state", "")).strip().upper()

    # Age check
    age = map_age_range(raw_age)
    if age is None or age < 18:
        return None

    sex = normalize_sex(raw_sex)
    race = normalize_race(raw_race)
    state = raw_state or "Unknown"
    region = STATE_TO_REGION.get(state, "Unknown")

    # --- Objective table (detailed demographics) ---
    obj_key = f"{MODEL}_objective_table_persona"
    obj = safe_parse_json(row.get(obj_key, "{}"))

    education = obj.get("EDUCATION") or obj.get("Education") or ""
    employment_status = obj.get("EMPLOYMENT_STATUS") or obj.get("Employment Status") or ""
    income_raw = obj.get("INCOME") or obj.get("Income") or ""
    marital_status = obj.get("MARITAL_STATUS") or obj.get("Marital Status") or obj.get("MARITAL STATUS") or ""
    ancestry = obj.get("ANCESTRY") or obj.get("Ancestry") or ""
    household_language = obj.get("HOUSEHOLD_LANGUAGE") or obj.get("Household Language") or "English"
    citizenship = obj.get("CITIZENSHIP") or obj.get("Citizenship") or ""
    veteran_status = obj.get("VETERAN_STATUS") or obj.get("Veteran Status") or ""
    health_insurance = obj.get("HEALTH_INSURANCE") or obj.get("Health Insurance") or ""
    job_description = obj.get("DETAILED_JOB_DESCRIPTION") or obj.get("Detailed Job Description") or ""

    # Clean income string
    income_str = str(income_raw).replace(",", "").replace("$", "").strip()
    try:
        income_val = int(re.sub(r'[^\d]', '', income_str))
        # Categorize relative to US median (~$60k)
        if income_val < 35000:
            income_level = "Low"
        elif income_val < 90000:
            income_level = "Middle"
        else:
            income_level = "High"
    except (ValueError, TypeError):
        income_level = income_str if income_str else "Unknown"

    # --- Subjective table (personality, political views, religion) ---
    subj_key = f"{MODEL}_subjective_table_persona"
    subj = safe_parse_json(row.get(subj_key, "{}"))

    ideology = subj.get("IDEOLOGY") or subj.get("Ideology") or ""
    political_views = subj.get("POLITICAL_VIEWS") or subj.get("Political Views") or subj.get("POLITICAL VIEWS") or ""
    religion = subj.get("RELIGION") or subj.get("Religion") or ""
    lifestyle = subj.get("LIFESTYLE") or subj.get("Lifestyle") or ""
    defining_quirks = subj.get("DEFINING_QUIRKS") or subj.get("Defining Quirks") or ""
    mannerisms = subj.get("MANNERISMS") or subj.get("Mannerisms") or ""
    personal_time = subj.get("PERSONAL_TIME") or subj.get("Personal Time") or ""
    big_five_raw = subj.get("BIG_FIVE_SCORES") or subj.get("Big Five Scores") or subj.get("BIG FIVE SCORES")
    big_five = parse_big_five(big_five_raw)

    # Map ideology to standardized political_orientation
    ideology_lower = str(ideology).lower()
    if any(x in ideology_lower for x in ["very liberal", "far left", "progressive", "socialist"]):
        political_orientation = "Very liberal"
    elif any(x in ideology_lower for x in ["liberal", "left-leaning", "left of center"]):
        political_orientation = "Liberal"
    elif any(x in ideology_lower for x in ["very conservative", "far right", "hard right"]):
        political_orientation = "Very conservative"
    elif any(x in ideology_lower for x in ["conservative", "right-leaning", "right of center"]):
        political_orientation = "Conservative"
    elif any(x in ideology_lower for x in ["moderate", "centrist", "independent", "center"]):
        political_orientation = "Moderate"
    else:
        political_orientation = ideology or "Unknown"

    # Map ideology to party (rough heuristic for US context)
    party = "Independent"
    if any(x in ideology_lower for x in ["liberal", "progressive", "democrat"]):
        party = "Democrat"
    elif any(x in ideology_lower for x in ["conservative", "republican"]):
        party = "Republican"
    elif "libertarian" in ideology_lower:
        party = "Libertarian"

    # --- Descriptive persona (narrative bio) ---
    bio_key = f"{MODEL}_descriptive_persona"
    bio = str(row.get(bio_key, "")).strip()
    # Strip outer quotes if wrapped
    if bio.startswith('"') and bio.endswith('"'):
        try:
            bio = json.loads(bio)
        except Exception:
            bio = bio[1:-1]

    # Extract name from bio
    name = extract_name_from_bio(bio)

    # Build normalized persona
    persona = {
        # IDs and location
        "country": "United States",
        "country_code": "US",
        "state": state,
        "region": region,

        # Core demographics (Census-grounded via meta_persona)
        "age": age,
        "gender": sex,
        "race": race,          # backward-compat alias → [RACE]
        "ethnicity": race,

        # Structured demographics (LLM-generated from Census constraints)
        "education": str(education),
        "employment_status": str(employment_status),
        "income_level": str(income_level),
        "marital_status": str(marital_status),
        "ancestry": str(ancestry),
        "household_language": str(household_language),
        "citizenship": str(citizenship),
        "veteran_status": str(veteran_status),
        "health_insurance": str(health_insurance),
        "job_description": str(job_description),

        # Psychographic / political (subjective table)
        "political_orientation": str(political_orientation),
        "political_party": str(party),
        "party": str(party),   # backward-compat alias → [PARTY]
        "ideology_raw": str(ideology),
        "political_views": str(political_views),
        "religion": str(religion),
        "lifestyle": str(lifestyle),
        "hobbies": str(personal_time),
        "defining_quirks": str(defining_quirks),
        "mannerisms": str(mannerisms),
        "big_five": str(big_five) if big_five else "",

        # Open-text biography (descriptive tier)
        "bio": bio,
        "name": name or "",

        # Stratification keys (for internal use)
        "_age_bucket": get_age_bucket(age),
        "_race_key": normalize_race(race) if normalize_race(race) in RACE_TARGETS else "Other",
        "_sex_key": "Female" if sex == "Woman" else "Male",
    }

    return persona


# ---------------------------------------------------------------------------
# Stratified sampling
# ---------------------------------------------------------------------------

def stratify(personas, target_n):
    """
    Stratified sampling by race × sex × age_bucket to match Census targets.
    Returns target_n personas.
    """
    from collections import defaultdict
    import random
    random.seed(42)

    # Build strata
    strata = defaultdict(list)
    for p in personas:
        race_k = p.get("_race_key", "Other")
        sex_k = p.get("_sex_key", "Male")
        age_k = p.get("_age_bucket")
        if age_k is None:
            continue
        key = (race_k, sex_k, age_k)
        strata[key].append(p)

    # Compute target counts per stratum
    result = []
    allocated = 0
    stratum_targets = {}
    for race_k, race_w in RACE_TARGETS.items():
        for sex_k, sex_w in SEX_TARGETS.items():
            for age_k, age_w in AGE_TARGETS.items():
                key = (race_k, sex_k, age_k)
                count = round(target_n * race_w * sex_w * age_w)
                stratum_targets[key] = count

    # Allocate from each stratum
    for key, target_count in sorted(stratum_targets.items()):
        pool = strata.get(key, [])
        if not pool:
            continue
        if len(pool) >= target_count:
            sampled = random.sample(pool, target_count)
        else:
            # Oversample with replacement if we don't have enough
            sampled = pool.copy()
            while len(sampled) < target_count:
                sampled.extend(random.sample(pool, min(len(pool), target_count - len(sampled))))
            sampled = sampled[:target_count]
        result.extend(sampled)

    # Shuffle and trim to exact target
    random.shuffle(result)
    result = result[:target_n]

    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _finalize_personas(selected):
    final_personas = []
    for i, p in enumerate(selected, start=1):
        p = {k: v for k, v in p.items() if not k.startswith("_")}
        p["id"] = f"us_{i:05d}"
        final_personas.append(p)
    return final_personas


def _build_metadata(final_personas, *, sampling_strategy, target_n=None):
    from collections import Counter

    race_dist = Counter(p["race"] for p in final_personas)
    sex_dist = Counter(p["gender"] for p in final_personas)
    age_dist = Counter(
        "18-29" if p["age"] < 30 else
        "30-44" if p["age"] < 45 else
        "45-59" if p["age"] < 60 else "60+"
        for p in final_personas
    )
    region_dist = Counter(p.get("region", "Unknown") for p in final_personas)

    if sampling_strategy == "stratified":
        description = (
            "10,000 US personas from Tianyi-Lab/Personas (arXiv:2503.16527, NeurIPS 2025). "
            "Census-grounded demographics (age, sex, race, state sampled from US Census joint distributions). "
            "LLM-generated text fields use Llama-3.1-70B-Instruct tier. "
            "Stratified to match 2023 US Census distributions by race × sex × age. "
            "Each persona includes: structured demographics, political views, personality (Big Five), "
            "religion, lifestyle, and a 1,000–5,000 character narrative biography."
        )
        usage = (
            "Load as DataFrame: pd.DataFrame(json.load(open('us_personas.json'))['personas']). "
            "Compatible with Lab in simulate/lab.py. For the expert_simulation prompt, use the [BIO] tag "
            "to include the narrative biography. The [NAME] tag provides the persona's name for natural self-reference."
        )
    else:
        description = (
            "Full adult-US persona database from Tianyi-Lab/Personas (arXiv:2503.16527, NeurIPS 2025). "
            "Includes all normalized US personas aged 18+ from the streamed dataset, without the 10,000-person "
            "stratified cap. LLM-generated text fields use Llama-3.1-70B-Instruct tier."
        )
        usage = (
            "Load as DataFrame: pd.DataFrame(json.load(open('us_personas_full.json'))['personas']). "
            "Use when you need the widest available US pool for quota sampling or rare subgroup analysis."
        )

    return {
        "description": description,
        "version": "1.1",
        "created": "2026-03-25",
        "source": "Tianyi-Lab/Personas",
        "source_paper": "arXiv:2503.16527 — LLM Generated Persona is a Promise with a Catch (NeurIPS 2025)",
        "source_url": "https://huggingface.co/datasets/Tianyi-Lab/Personas",
        "model_tier": MODEL,
        "sampling_strategy": sampling_strategy,
        "target_personas": target_n,
        "total_personas": len(final_personas),
        "country": "United States",
        "actual_distributions": {
            "race": dict(race_dist),
            "gender": dict(sex_dist),
            "age_group": dict(age_dist),
            "region": dict(region_dist),
        },
        "fields": [
            "id", "country", "country_code", "state", "region",
            "age", "gender", "race", "ethnicity",
            "education", "employment_status", "income_level", "marital_status",
            "ancestry", "household_language", "citizenship", "veteran_status",
            "health_insurance", "job_description",
            "political_orientation", "political_party", "party",
            "ideology_raw", "political_views", "religion",
            "lifestyle", "hobbies", "defining_quirks", "mannerisms", "big_five",
            "bio", "name",
        ],
        "tag_aliases": {
            "[AGE]": "age",
            "[GENDER]": "gender",
            "[RACE]": "race",
            "[EDUCATION]": "education",
            "[EMPLOYMENT_STATUS]": "employment_status",
            "[INCOME_LEVEL]": "income_level",
            "[MARITAL_STATUS]": "marital_status",
            "[PARTY]": "party",
            "[POLITICAL_ORIENTATION]": "political_orientation",
            "[RELIGION]": "religion",
            "[STATE]": "state",
            "[BIO]": "bio",
            "[NAME]": "name",
            "[LIFESTYLE]": "lifestyle",
            "[HOBBIES]": "hobbies",
            "[BIG_FIVE]": "big_five",
        },
        "usage": usage,
    }


def build_database(target_n=TARGET_N, full=False):
    try:
        from datasets import load_dataset
    except ImportError:
        print("ERROR: 'datasets' library not found. Install with: pip install datasets")
        sys.exit(1)

    print(f"Loading Tianyi-Lab/Personas from HuggingFace (streaming)...")
    print("This may take a few minutes on first run (caches locally after).")

    ds = load_dataset(
        "Tianyi-Lab/Personas",
        split="train",
        streaming=True,
    )

    raw_personas = []
    skipped = 0
    print("Parsing personas...", flush=True)

    for i, row in enumerate(ds):
        persona = normalize_persona(row)
        if persona is None:
            skipped += 1
            continue
        raw_personas.append(persona)

        if (i + 1) % 5000 == 0:
            print(f"  Processed {i+1} rows, kept {len(raw_personas)} valid personas...", flush=True)

    print(f"Done. Total rows: {i+1}, valid personas: {len(raw_personas)}, skipped (under 18): {skipped}")

    if full:
        print("Building full uncapped adult-US persona database...")
        selected = raw_personas
        sampling_strategy = "full"
    elif len(raw_personas) < target_n:
        print(f"WARNING: Only {len(raw_personas)} valid personas available; using all of them.")
        selected = raw_personas
        sampling_strategy = "full"
    else:
        print(f"Stratifying to {target_n} personas (Census-weighted)...")
        selected = stratify(raw_personas, target_n)
        sampling_strategy = "stratified"

    final_personas = _finalize_personas(selected)

    database = {
        "metadata": _build_metadata(
            final_personas,
            sampling_strategy=sampling_strategy,
            target_n=target_n if sampling_strategy == "stratified" else None,
        ),
        "personas": final_personas,
    }

    return database


def _parse_args():
    parser = argparse.ArgumentParser(description="Build the US persona database from Tianyi-Lab/Personas.")
    parser.add_argument(
        "--full",
        action="store_true",
        help="Build the full uncapped adult-US dataset instead of the 10,000-person stratified sample.",
    )
    parser.add_argument(
        "--target-n",
        type=int,
        default=TARGET_N,
        help="Target size for the stratified sample build. Ignored when --full is set.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional output filename. Defaults to us_personas.json or us_personas_full.json based on mode.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    db = build_database(target_n=args.target_n, full=args.full)
    output_filename = args.output or (FULL_OUTPUT_FILENAME if args.full else DEFAULT_OUTPUT_FILENAME)
    out_path = os.path.join(os.path.dirname(__file__), output_filename)
    print(f"Writing {db['metadata']['total_personas']} personas to {out_path}...")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)
    print(f"Done. File size: {os.path.getsize(out_path) / 1e6:.1f} MB")
    print()
    print("Distribution:")
    for k, v in db["metadata"]["actual_distributions"].items():
        print(f"  {k}: {dict(sorted(v.items(), key=lambda x: -x[1]))}")
