"""
build_personas.py — Generate the human-ai-eval persona database.

Produces simulate/personas/personas.json: demographically representative personas for 6 countries,
suitable for persona prompting in the human-ai-eval framework via [TAG] substitution.

Sources & references:
  US:      US Census Bureau 2023, Pew Research Center 2023
  India:   Census of India 2011 (projected 2023), ISSP 2022, Lokniti-CSDS
  Germany: Statistisches Bundesamt 2023, ALLBUS 2023 (arXiv:2511.21722)
  Brazil:  IBGE Census 2022, Datafolha 2023
  Nigeria: NBS 2023, Afrobarometer Round 9
  Japan:   Statistics Bureau of Japan 2023, NHK Survey 2023

Design follows best practices from:
  - "German General Personas" (arXiv:2511.21722): census-grounded individual profiles
  - "PERSONA Testbed" (arXiv:2407.17387): US Census sampling + psychographic attributes
  - "Assessing Reliability of Persona-Conditioned LLMs" (arXiv:2602.18462): 8-dim demographics
  - "SocioBench" (arXiv:2510.11131): 40+ features, 30+ country coverage

Run:
  python build_personas.py
  # Writes simulate/personas/personas.json (~180 personas, 30 per country)

Fields per persona (all compatible with format_personalization() [TAG] system):
  id, country, country_code, age, gender, education, employment_status,
  income_level, urban_rural, marital_status, religion, political_orientation,
  political_party, ethnicity, race (=ethnicity alias), party (=political_party alias)
"""

import json
import os

# ---------------------------------------------------------------------------
# Country definitions: list of persona dicts, each with all demographic fields.
# Stratified to match real census/survey distributions.
# ---------------------------------------------------------------------------

US_PERSONAS = [
    # --- Young adults 18-24 (4 personas) ---
    {"age": 19, "gender": "Man", "education": "Some college", "employment_status": "Part-time / student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Secular", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Hispanic"},
    {"age": 22, "gender": "Woman", "education": "Some college", "employment_status": "Part-time / student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Protestant", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Black / African American"},
    {"age": 21, "gender": "Man", "education": "High school diploma / GED", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 23, "gender": "Non-binary", "education": "Some college", "employment_status": "Part-time / student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Secular", "political_orientation": "Very liberal",
     "political_party": "Democrat", "ethnicity": "White"},
    # --- 25-34 (6 personas) ---
    {"age": 27, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Catholic", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Hispanic"},
    {"age": 31, "gender": "Man", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Moderate",
     "political_party": "Independent", "ethnicity": "White"},
    {"age": 29, "gender": "Woman", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Jewish", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "White"},
    {"age": 33, "gender": "Man", "education": "High school diploma / GED", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 28, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Secular", "political_orientation": "Moderate",
     "political_party": "Independent", "ethnicity": "Asian American"},
    {"age": 30, "gender": "Man", "education": "Some college", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "Black / African American"},
    # --- 35-44 (6 personas) ---
    {"age": 38, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Moderate",
     "political_party": "Democrat", "ethnicity": "White"},
    {"age": 42, "gender": "Man", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 36, "gender": "Man", "education": "Some college", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Moderate",
     "political_party": "Independent", "ethnicity": "Hispanic"},
    {"age": 40, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Divorced",
     "religion": "Protestant", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Black / African American"},
    {"age": 44, "gender": "Man", "education": "High school diploma / GED", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Very conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 37, "gender": "Woman", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Asian American"},
    # --- 45-54 (5 personas) ---
    {"age": 48, "gender": "Man", "education": "Some college", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 52, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Moderate",
     "political_party": "Independent", "ethnicity": "White"},
    {"age": 46, "gender": "Man", "education": "High school diploma / GED", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 50, "gender": "Woman", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Black / African American"},
    {"age": 54, "gender": "Man", "education": "Bachelor's degree", "employment_status": "Self-employed",
     "income_level": "High", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Muslim", "political_orientation": "Moderate",
     "political_party": "Democrat", "ethnicity": "Black / African American"},
    # --- 55-64 (5 personas) ---
    {"age": 58, "gender": "Woman", "education": "High school diploma / GED", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 62, "gender": "Man", "education": "Some college", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Moderate",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 57, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Divorced",
     "religion": "None / Secular", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Hispanic"},
    {"age": 60, "gender": "Man", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 63, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Part-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Widowed",
     "religion": "Protestant", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "Black / African American"},
    # --- 65+ (4 personas) ---
    {"age": 68, "gender": "Man", "education": "High school diploma / GED", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant", "political_orientation": "Very conservative",
     "political_party": "Republican", "ethnicity": "White"},
    {"age": 72, "gender": "Woman", "education": "Some college", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Widowed",
     "religion": "Catholic", "political_orientation": "Moderate",
     "political_party": "Independent", "ethnicity": "White"},
    {"age": 74, "gender": "Man", "education": "Graduate degree", "employment_status": "Retired",
     "income_level": "High", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Jewish", "political_orientation": "Liberal",
     "political_party": "Democrat", "ethnicity": "White"},
    {"age": 78, "gender": "Woman", "education": "Less than high school", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Widowed",
     "religion": "Protestant", "political_orientation": "Conservative",
     "political_party": "Republican", "ethnicity": "White"},
]

INDIA_PERSONAS = [
    # --- 18-24 (9 personas) ---
    {"age": 20, "gender": "Man", "education": "Secondary school (Class 10-12)", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Hindu", "political_orientation": "Centre-right",
     "political_party": "BJP", "ethnicity": "OBC (Other Backward Class)"},
    {"age": 22, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Student",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "Indian National Congress", "ethnicity": "General / Upper caste"},
    {"age": 19, "gender": "Man", "education": "Primary school (up to Class 8)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "Regional party", "ethnicity": "SC (Scheduled Caste / Dalit)"},
    {"age": 21, "gender": "Woman", "education": "Secondary school (Class 10-12)", "employment_status": "Unemployed",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim", "political_orientation": "Centre-left",
     "political_party": "Samajwadi Party", "ethnicity": "Muslim OBC"},
    {"age": 23, "gender": "Man", "education": "Secondary school (Class 10-12)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Semi-urban", "marital_status": "Single",
     "religion": "Hindu", "political_orientation": "Right",
     "political_party": "BJP", "ethnicity": "OBC (Other Backward Class)"},
    {"age": 18, "gender": "Woman", "education": "Primary school (up to Class 8)", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "Regional party", "ethnicity": "ST (Scheduled Tribe / Adivasi)"},
    {"age": 24, "gender": "Man", "education": "Bachelor's degree", "employment_status": "Employed",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Hindu", "political_orientation": "Centre-left",
     "political_party": "AAP (Aam Aadmi Party)", "ethnicity": "General / Upper caste"},
    {"age": 20, "gender": "Woman", "education": "Secondary school (Class 10-12)", "employment_status": "Student",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian", "political_orientation": "Centre-left",
     "political_party": "Indian National Congress", "ethnicity": "ST (Scheduled Tribe / Adivasi)"},
    {"age": 22, "gender": "Man", "education": "Primary school (up to Class 8)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Muslim", "political_orientation": "Centre",
     "political_party": "Indian National Congress", "ethnicity": "Muslim OBC"},
    # --- 25-34 (9 personas) ---
    {"age": 28, "gender": "Man", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Right",
     "political_party": "BJP", "ethnicity": "General / Upper caste"},
    {"age": 31, "gender": "Woman", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "AAP (Aam Aadmi Party)", "ethnicity": "OBC (Other Backward Class)"},
    {"age": 26, "gender": "Man", "education": "Secondary school (Class 10-12)", "employment_status": "Self-employed",
     "income_level": "Middle", "urban_rural": "Semi-urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre-right",
     "political_party": "BJP", "ethnicity": "OBC (Other Backward Class)"},
    {"age": 33, "gender": "Woman", "education": "Primary school (up to Class 8)", "employment_status": "Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "Regional party", "ethnicity": "SC (Scheduled Caste / Dalit)"},
    {"age": 29, "gender": "Man", "education": "Secondary school (Class 10-12)", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim", "political_orientation": "Centre",
     "political_party": "Indian National Congress", "ethnicity": "Muslim OBC"},
    {"age": 27, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Sikh", "political_orientation": "Centre",
     "political_party": "Indian National Congress", "ethnicity": "General / Upper caste"},
    {"age": 34, "gender": "Man", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Right",
     "political_party": "BJP", "ethnicity": "General / Upper caste"},
    {"age": 25, "gender": "Man", "education": "Primary school (up to Class 8)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre-left",
     "political_party": "Regional party", "ethnicity": "ST (Scheduled Tribe / Adivasi)"},
    {"age": 32, "gender": "Woman", "education": "Secondary school (Class 10-12)", "employment_status": "Self-employed",
     "income_level": "Middle", "urban_rural": "Semi-urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre-right",
     "political_party": "BJP", "ethnicity": "OBC (Other Backward Class)"},
    # --- 35-44 (6 personas) ---
    {"age": 38, "gender": "Man", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre-right",
     "political_party": "BJP", "ethnicity": "General / Upper caste"},
    {"age": 42, "gender": "Woman", "education": "Secondary school (Class 10-12)", "employment_status": "Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "Regional party", "ethnicity": "OBC (Other Backward Class)"},
    {"age": 36, "gender": "Man", "education": "Primary school (up to Class 8)", "employment_status": "Farmer / agricultural",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre-left",
     "political_party": "Regional party", "ethnicity": "SC (Scheduled Caste / Dalit)"},
    {"age": 40, "gender": "Woman", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Muslim", "political_orientation": "Centre-left",
     "political_party": "Indian National Congress", "ethnicity": "Muslim OBC"},
    {"age": 44, "gender": "Man", "education": "Secondary school (Class 10-12)", "employment_status": "Self-employed",
     "income_level": "Middle", "urban_rural": "Semi-urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Right",
     "political_party": "BJP", "ethnicity": "OBC (Other Backward Class)"},
    {"age": 39, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian", "political_orientation": "Centre",
     "political_party": "Indian National Congress", "ethnicity": "General / Upper caste"},
    # --- 45-54 (4 personas) ---
    {"age": 48, "gender": "Man", "education": "Primary school (up to Class 8)", "employment_status": "Farmer / agricultural",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "Regional party", "ethnicity": "SC (Scheduled Caste / Dalit)"},
    {"age": 52, "gender": "Woman", "education": "Secondary school (Class 10-12)", "employment_status": "Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim", "political_orientation": "Centre",
     "political_party": "Indian National Congress", "ethnicity": "Muslim OBC"},
    {"age": 50, "gender": "Man", "education": "Graduate degree", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Right",
     "political_party": "BJP", "ethnicity": "General / Upper caste"},
    {"age": 46, "gender": "Woman", "education": "Bachelor's degree", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre-left",
     "political_party": "AAP (Aam Aadmi Party)", "ethnicity": "OBC (Other Backward Class)"},
    # --- 55+ (2 personas) ---
    {"age": 62, "gender": "Man", "education": "Primary school (up to Class 8)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Hindu", "political_orientation": "Centre-right",
     "political_party": "BJP", "ethnicity": "OBC (Other Backward Class)"},
    {"age": 70, "gender": "Woman", "education": "No formal education", "employment_status": "Retired / Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Widowed",
     "religion": "Hindu", "political_orientation": "Centre",
     "political_party": "Regional party", "ethnicity": "SC (Scheduled Caste / Dalit)"},
]

GERMANY_PERSONAS = [
    # --- 18-29 (5 personas) ---
    {"age": 20, "gender": "Man", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Konfessionslos", "political_orientation": "Left",
     "political_party": "Die Grünen", "ethnicity": "German"},
    {"age": 24, "gender": "Woman", "education": "Abitur / University entrance qualification", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Konfessionslos", "political_orientation": "Left",
     "political_party": "SPD", "ethnicity": "German"},
    {"age": 22, "gender": "Man", "education": "Hauptschulabschluss", "employment_status": "Employed / Apprenticeship",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Right",
     "political_party": "AfD", "ethnicity": "German"},
    {"age": 27, "gender": "Woman", "education": "University degree (Bachelor's / Master's)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Konfessionslos", "political_orientation": "Centre-left",
     "political_party": "Die Grünen", "ethnicity": "Turkish-German"},
    {"age": 26, "gender": "Diverse (non-binary)", "education": "Abitur / University entrance qualification", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Konfessionslos", "political_orientation": "Far left",
     "political_party": "Die Linke", "ethnicity": "German"},
    # --- 30-44 (7 personas) ---
    {"age": 33, "gender": "Man", "education": "University degree (Bachelor's / Master's)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Konfessionslos", "political_orientation": "Centre-left",
     "political_party": "SPD", "ethnicity": "German"},
    {"age": 38, "gender": "Woman", "education": "University degree (Bachelor's / Master's)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 35, "gender": "Man", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Centre-right",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 41, "gender": "Woman", "education": "Hauptschulabschluss", "employment_status": "Part-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre",
     "political_party": "CSU", "ethnicity": "German"},
    {"age": 43, "gender": "Man", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "SPD", "ethnicity": "Turkish-German"},
    {"age": 37, "gender": "Woman", "education": "University degree (Bachelor's / Master's)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Konfessionslos", "political_orientation": "Centre-left",
     "political_party": "SPD", "ethnicity": "Other non-German"},
    {"age": 44, "gender": "Man", "education": "Abitur / University entrance qualification", "employment_status": "Self-employed",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Konfessionslos", "political_orientation": "Centre-right",
     "political_party": "FDP", "ethnicity": "German"},
    # --- 45-59 (8 personas) ---
    {"age": 48, "gender": "Man", "education": "Hauptschulabschluss", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Right",
     "political_party": "AfD", "ethnicity": "German"},
    {"age": 52, "gender": "Woman", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Part-time",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre-right",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 55, "gender": "Man", "education": "University degree (Bachelor's / Master's)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Centre-right",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 46, "gender": "Woman", "education": "University degree (Bachelor's / Master's)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Konfessionslos", "political_orientation": "Centre-left",
     "political_party": "Die Grünen", "ethnicity": "German"},
    {"age": 58, "gender": "Man", "education": "Hauptschulabschluss", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 50, "gender": "Woman", "education": "Abitur / University entrance qualification", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Divorced",
     "religion": "None / Konfessionslos", "political_orientation": "Left",
     "political_party": "Die Linke", "ethnicity": "Other non-German"},
    {"age": 54, "gender": "Man", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Right",
     "political_party": "AfD", "ethnicity": "German"},
    {"age": 59, "gender": "Woman", "education": "University degree (Bachelor's / Master's)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre-right",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    # --- 60+ (10 personas) ---
    {"age": 63, "gender": "Man", "education": "Hauptschulabschluss", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Centre-right",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 67, "gender": "Woman", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 71, "gender": "Man", "education": "University degree (Bachelor's / Master's)", "employment_status": "Retired",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Centre-left",
     "political_party": "SPD", "ethnicity": "German"},
    {"age": 65, "gender": "Woman", "education": "Hauptschulabschluss", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Widowed",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre-right",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 74, "gender": "Man", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Right",
     "political_party": "AfD", "ethnicity": "German"},
    {"age": 69, "gender": "Woman", "education": "University degree (Bachelor's / Master's)", "employment_status": "Retired",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Konfessionslos", "political_orientation": "Left",
     "political_party": "SPD", "ethnicity": "German"},
    {"age": 77, "gender": "Man", "education": "Hauptschulabschluss", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Widowed",
     "religion": "Protestant (Evangelisch)", "political_orientation": "Centre",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 80, "gender": "Woman", "education": "Hauptschulabschluss", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Widowed",
     "religion": "Catholic (Römisch-katholisch)", "political_orientation": "Centre",
     "political_party": "CDU / CSU", "ethnicity": "German"},
    {"age": 64, "gender": "Man", "education": "Abitur / University entrance qualification", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "None / Konfessionslos", "political_orientation": "Centre-left",
     "political_party": "SPD", "ethnicity": "German"},
    {"age": 72, "gender": "Woman", "education": "Mittlere Reife (Realschulabschluss)", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "None / Konfessionslos", "political_orientation": "Centre",
     "political_party": "FDP", "ethnicity": "Other non-German"},
]

BRAZIL_PERSONAS = [
    # --- 18-24 (6 personas) ---
    {"age": 20, "gender": "Man", "education": "Ensino Médio (secondary school)", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Evangelical Protestant", "political_orientation": "Right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "Pardo (mixed race)"},
    {"age": 22, "gender": "Woman", "education": "Ensino Superior (university)", "employment_status": "Student",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / No religion", "political_orientation": "Left",
     "political_party": "PT (Partido dos Trabalhadores)", "ethnicity": "White"},
    {"age": 19, "gender": "Man", "education": "Ensino Fundamental (primary school)", "employment_status": "Unemployed",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "MDB", "ethnicity": "Black (Preto)"},
    {"age": 23, "gender": "Woman", "education": "Ensino Médio (secondary school)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Evangelical Protestant", "political_orientation": "Centre-right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "Pardo (mixed race)"},
    {"age": 24, "gender": "Man", "education": "Ensino Superior (university)", "employment_status": "Student",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Catholic", "political_orientation": "Centre-left",
     "political_party": "PT (Partido dos Trabalhadores)", "ethnicity": "White"},
    {"age": 21, "gender": "Woman", "education": "Ensino Fundamental (primary school)", "employment_status": "Unemployed",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Evangelical Protestant", "political_orientation": "Centre",
     "political_party": "PSD", "ethnicity": "Pardo (mixed race)"},
    # --- 25-34 (8 personas) ---
    {"age": 27, "gender": "Man", "education": "Ensino Médio (secondary school)", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Evangelical Protestant", "political_orientation": "Right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "Pardo (mixed race)"},
    {"age": 31, "gender": "Woman", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / No religion", "political_orientation": "Left",
     "political_party": "PSOL", "ethnicity": "White"},
    {"age": 29, "gender": "Man", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre-right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "White"},
    {"age": 33, "gender": "Woman", "education": "Ensino Fundamental (primary school)", "employment_status": "Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Evangelical Protestant", "political_orientation": "Right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "Pardo (mixed race)"},
    {"age": 26, "gender": "Man", "education": "Ensino Médio (secondary school)", "employment_status": "Self-employed",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "MDB", "ethnicity": "Black (Preto)"},
    {"age": 34, "gender": "Woman", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Spiritist / Kardecist", "political_orientation": "Centre-left",
     "political_party": "PT (Partido dos Trabalhadores)", "ethnicity": "White"},
    {"age": 28, "gender": "Man", "education": "Ensino Fundamental (primary school)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "PSD", "ethnicity": "Pardo (mixed race)"},
    {"age": 30, "gender": "Woman", "education": "Ensino Médio (secondary school)", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Evangelical Protestant", "political_orientation": "Centre-right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "Black (Preto)"},
    # --- 35-44 (7 personas) ---
    {"age": 38, "gender": "Man", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre-right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "White"},
    {"age": 40, "gender": "Woman", "education": "Ensino Médio (secondary school)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Evangelical Protestant", "political_orientation": "Right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "Pardo (mixed race)"},
    {"age": 36, "gender": "Man", "education": "Ensino Fundamental (primary school)", "employment_status": "Farmer / agricultural",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "MDB", "ethnicity": "Pardo (mixed race)"},
    {"age": 42, "gender": "Woman", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Divorced",
     "religion": "None / No religion", "political_orientation": "Left",
     "political_party": "PT (Partido dos Trabalhadores)", "ethnicity": "White"},
    {"age": 44, "gender": "Man", "education": "Ensino Médio (secondary school)", "employment_status": "Self-employed",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Evangelical Protestant", "political_orientation": "Right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "White"},
    {"age": 39, "gender": "Woman", "education": "Ensino Fundamental (primary school)", "employment_status": "Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "PSD", "ethnicity": "Pardo (mixed race)"},
    {"age": 43, "gender": "Man", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Spiritist / Kardecist", "political_orientation": "Centre-left",
     "political_party": "PT (Partido dos Trabalhadores)", "ethnicity": "White"},
    # --- 45-59 (6 personas) ---
    {"age": 48, "gender": "Man", "education": "Ensino Fundamental (primary school)", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Evangelical Protestant", "political_orientation": "Right",
     "political_party": "PL (Partido Liberal)", "ethnicity": "Black (Preto)"},
    {"age": 52, "gender": "Woman", "education": "Ensino Médio (secondary school)", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "MDB", "ethnicity": "Pardo (mixed race)"},
    {"age": 56, "gender": "Man", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre-right",
     "political_party": "PSDB", "ethnicity": "White"},
    {"age": 45, "gender": "Woman", "education": "Ensino Superior (university)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / No religion", "political_orientation": "Left",
     "political_party": "PT (Partido dos Trabalhadores)", "ethnicity": "White"},
    {"age": 58, "gender": "Man", "education": "Ensino Fundamental (primary school)", "employment_status": "Farmer / agricultural",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "MDB", "ethnicity": "Pardo (mixed race)"},
    {"age": 50, "gender": "Woman", "education": "Ensino Médio (secondary school)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Divorced",
     "religion": "Evangelical Protestant", "political_orientation": "Centre-right",
     "political_party": "PSD", "ethnicity": "Pardo (mixed race)"},
    # --- 60+ (3 personas) ---
    {"age": 63, "gender": "Man", "education": "Ensino Fundamental (primary school)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Catholic", "political_orientation": "Centre-left",
     "political_party": "PT (Partido dos Trabalhadores)", "ethnicity": "Black (Preto)"},
    {"age": 68, "gender": "Woman", "education": "Ensino Médio (secondary school)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Widowed",
     "religion": "Catholic", "political_orientation": "Centre",
     "political_party": "MDB", "ethnicity": "Pardo (mixed race)"},
    {"age": 71, "gender": "Man", "education": "Ensino Superior (university)", "employment_status": "Retired",
     "income_level": "High", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "None / No religion", "political_orientation": "Centre-right",
     "political_party": "PSDB", "ethnicity": "White"},
]

NIGERIA_PERSONAS = [
    # --- 18-24 (10 personas) ---
    {"age": 20, "gender": "Man", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre-right",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Hausa-Fulani"},
    {"age": 22, "gender": "Woman", "education": "Tertiary (BSc / HND)", "employment_status": "Student",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre-left",
     "political_party": "Labour Party", "ethnicity": "Igbo"},
    {"age": 19, "gender": "Man", "education": "Primary school", "employment_status": "Unemployed",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Hausa-Fulani"},
    {"age": 23, "gender": "Woman", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian (Pentecostal)", "political_orientation": "Left",
     "political_party": "Labour Party", "ethnicity": "Yoruba"},
    {"age": 21, "gender": "Man", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Student",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Igbo"},
    {"age": 24, "gender": "Woman", "education": "Tertiary (BSc / HND)", "employment_status": "Student",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Hausa-Fulani"},
    {"age": 18, "gender": "Man", "education": "Primary school", "employment_status": "Unemployed",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Single",
     "religion": "Christian (Catholic)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Other (Middle Belt / Delta)"},
    {"age": 22, "gender": "Woman", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Self-employed / trader",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre-left",
     "political_party": "Labour Party", "ethnicity": "Yoruba"},
    {"age": 20, "gender": "Man", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Employed",
     "income_level": "Low", "urban_rural": "Semi-urban", "marital_status": "Single",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre-right",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Other (Middle Belt / Delta)"},
    {"age": 23, "gender": "Woman", "education": "Tertiary (BSc / HND)", "employment_status": "Student",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Igbo"},
    # --- 25-34 (9 personas) ---
    {"age": 28, "gender": "Man", "education": "Tertiary (BSc / HND)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre-left",
     "political_party": "Labour Party", "ethnicity": "Igbo"},
    {"age": 31, "gender": "Woman", "education": "Tertiary (BSc / HND)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Hausa-Fulani"},
    {"age": 26, "gender": "Man", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Self-employed / trader",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Yoruba"},
    {"age": 33, "gender": "Woman", "education": "Primary school", "employment_status": "Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Hausa-Fulani"},
    {"age": 29, "gender": "Man", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Farmer",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Traditional / Animist", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Other (Middle Belt / Delta)"},
    {"age": 27, "gender": "Woman", "education": "Tertiary (BSc / HND)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian (Catholic)", "political_orientation": "Left",
     "political_party": "Labour Party", "ethnicity": "Igbo"},
    {"age": 34, "gender": "Man", "education": "Tertiary (BSc / HND)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre-right",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Hausa-Fulani"},
    {"age": 25, "gender": "Woman", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Self-employed / trader",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Yoruba"},
    {"age": 32, "gender": "Man", "education": "Primary school", "employment_status": "Farmer",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Hausa-Fulani"},
    # --- 35-44 (6 personas) ---
    {"age": 38, "gender": "Man", "education": "Tertiary (BSc / HND)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre-left",
     "political_party": "Labour Party", "ethnicity": "Igbo"},
    {"age": 40, "gender": "Woman", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Self-employed / trader",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Hausa-Fulani"},
    {"age": 36, "gender": "Man", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Farmer",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Other (Middle Belt / Delta)"},
    {"age": 43, "gender": "Woman", "education": "Tertiary (BSc / HND)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian (Pentecostal)", "political_orientation": "Left",
     "political_party": "Labour Party", "ethnicity": "Yoruba"},
    {"age": 41, "gender": "Man", "education": "Primary school", "employment_status": "Farmer",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Traditional / Animist", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Other (Middle Belt / Delta)"},
    {"age": 44, "gender": "Woman", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Homemaker",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Hausa-Fulani"},
    # --- 45-59 (4 personas) ---
    {"age": 48, "gender": "Man", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Self-employed / trader",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian (Catholic)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Igbo"},
    {"age": 52, "gender": "Woman", "education": "Primary school", "employment_status": "Farmer",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Hausa-Fulani"},
    {"age": 55, "gender": "Man", "education": "Tertiary (BSc / HND)", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre-right",
     "political_party": "APC (All Progressives Congress)", "ethnicity": "Yoruba"},
    {"age": 50, "gender": "Woman", "education": "Secondary school (SSCE / WAEC)", "employment_status": "Self-employed / trader",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Christian (Pentecostal)", "political_orientation": "Centre-left",
     "political_party": "Labour Party", "ethnicity": "Igbo"},
    # --- 60+ (1 persona) ---
    {"age": 65, "gender": "Man", "education": "Primary school", "employment_status": "Retired / Elder",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Muslim (Sunni)", "political_orientation": "Centre",
     "political_party": "PDP (Peoples Democratic Party)", "ethnicity": "Hausa-Fulani"},
]

JAPAN_PERSONAS = [
    # --- 18-29 (5 personas) ---
    {"age": 20, "gender": "Man", "education": "University / Junior college (in progress)", "employment_status": "Student",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre",
     "political_party": "None / Independent (Mushozoku)", "ethnicity": "Japanese"},
    {"age": 24, "gender": "Woman", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Secular", "political_orientation": "Centre-left",
     "political_party": "CDP (Constitutional Democratic Party)", "ethnicity": "Japanese"},
    {"age": 22, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Suburban", "marital_status": "Single",
     "religion": "None / Secular", "political_orientation": "Centre",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 27, "gender": "Woman", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Secular", "political_orientation": "Left",
     "political_party": "CDP (Constitutional Democratic Party)", "ethnicity": "Japanese"},
    {"age": 25, "gender": "Man", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre-right",
     "political_party": "Nippon Ishin no Kai", "ethnicity": "Japanese"},
    # --- 30-44 (7 personas) ---
    {"age": 33, "gender": "Man", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Centre",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 37, "gender": "Woman", "education": "University graduate", "employment_status": "Part-time",
     "income_level": "Low", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre",
     "political_party": "Kōmeitō", "ethnicity": "Japanese"},
    {"age": 40, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 35, "gender": "Woman", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Single",
     "religion": "None / Secular", "political_orientation": "Left",
     "political_party": "CDP (Constitutional Democratic Party)", "ethnicity": "Japanese"},
    {"age": 43, "gender": "Man", "education": "University graduate", "employment_status": "Self-employed",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Centre-right",
     "political_party": "Nippon Ishin no Kai", "ethnicity": "Japanese"},
    {"age": 38, "gender": "Woman", "education": "High school (Kōkō)", "employment_status": "Part-time",
     "income_level": "Low", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre",
     "political_party": "None / Independent (Mushozoku)", "ethnicity": "Japanese"},
    {"age": 44, "gender": "Man", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Zainichi Korean"},
    # --- 45-59 (7 personas) ---
    {"age": 48, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 52, "gender": "Woman", "education": "High school (Kōkō)", "employment_status": "Part-time",
     "income_level": "Low", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre",
     "political_party": "Kōmeitō", "ethnicity": "Japanese"},
    {"age": 55, "gender": "Man", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 46, "gender": "Woman", "education": "University graduate", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Centre-left",
     "political_party": "CDP (Constitutional Democratic Party)", "ethnicity": "Japanese"},
    {"age": 58, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Employed full-time",
     "income_level": "Middle", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 50, "gender": "Woman", "education": "University graduate", "employment_status": "Part-time",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Divorced",
     "religion": "None / Secular", "political_orientation": "Left",
     "political_party": "Japanese Communist Party", "ethnicity": "Japanese"},
    {"age": 54, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Self-employed",
     "income_level": "Middle", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre",
     "political_party": "None / Independent (Mushozoku)", "ethnicity": "Japanese"},
    # --- 60+ (11 personas) ---
    {"age": 63, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 67, "gender": "Woman", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Suburban", "marital_status": "Married",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre",
     "political_party": "Kōmeitō", "ethnicity": "Japanese"},
    {"age": 71, "gender": "Man", "education": "University graduate", "employment_status": "Retired",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 65, "gender": "Woman", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Widowed",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 74, "gender": "Man", "education": "University graduate", "employment_status": "Retired",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 68, "gender": "Woman", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre-left",
     "political_party": "CDP (Constitutional Democratic Party)", "ethnicity": "Japanese"},
    {"age": 77, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre-right",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
    {"age": 80, "gender": "Woman", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Urban", "marital_status": "Widowed",
     "religion": "Buddhist (nominal)", "political_orientation": "Centre",
     "political_party": "None / Independent (Mushozoku)", "ethnicity": "Japanese"},
    {"age": 62, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Middle", "urban_rural": "Rural", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Left",
     "political_party": "Japanese Communist Party", "ethnicity": "Japanese"},
    {"age": 72, "gender": "Woman", "education": "University graduate", "employment_status": "Retired",
     "income_level": "High", "urban_rural": "Urban", "marital_status": "Married",
     "religion": "None / Secular", "political_orientation": "Centre-left",
     "political_party": "CDP (Constitutional Democratic Party)", "ethnicity": "Japanese"},
    {"age": 78, "gender": "Man", "education": "High school (Kōkō)", "employment_status": "Retired",
     "income_level": "Low", "urban_rural": "Suburban", "marital_status": "Widowed",
     "religion": "Shinto / Buddhist (dual)", "political_orientation": "Centre",
     "political_party": "LDP (Liberal Democratic Party)", "ethnicity": "Japanese"},
]


# ---------------------------------------------------------------------------
# Country metadata: full name, ISO code, demographic distribution notes
# ---------------------------------------------------------------------------

COUNTRY_META = {
    "US": {
        "name": "United States",
        "code": "US",
        "personas": US_PERSONAS,
        "notes": "Demographics based on US Census Bureau 2023 and Pew Research Center 2023. "
                 "Racial composition: White 60%, Hispanic 19%, Black 13%, Asian 6%, Other 2%. "
                 "Political affiliation: Democrat 31%, Republican 27%, Independent 38%. "
                 "Education: <HS 8%, HS diploma 28%, Some college 29%, Bachelor's 20%, Graduate 13%.",
    },
    "India": {
        "name": "India",
        "code": "IN",
        "personas": INDIA_PERSONAS,
        "notes": "Demographics based on Census of India 2011 (projected 2023), ISSP 2022, Lokniti-CSDS. "
                 "Religious composition: Hindu 79%, Muslim 14%, Christian 2.3%, Sikh 1.7%, Other 3%. "
                 "Caste: General 27%, OBC 41%, SC 19%, ST 8%. Urban/Rural: 35% urban, 65% rural. "
                 "Education reflects urban-rural and caste-based disparities.",
    },
    "Germany": {
        "name": "Germany",
        "code": "DE",
        "personas": GERMANY_PERSONAS,
        "notes": "Demographics based on Statistisches Bundesamt 2023 and ALLBUS 2023 (arXiv:2511.21722). "
                 "Age-skewed older: median age 45.7. Religion: Protestant 25%, Catholic 27%, Muslim 5%, None 38%. "
                 "Education tiers: Hauptschule, Realschule, Abitur, University. "
                 "Political: CDU/CSU 28%, SPD 26%, Greens 14%, AfD 10%, FDP 7%, Left 5%.",
    },
    "Brazil": {
        "name": "Brazil",
        "code": "BR",
        "personas": BRAZIL_PERSONAS,
        "notes": "Demographics based on IBGE Census 2022 and Datafolha 2023. "
                 "Racial: White 43%, Pardo 46%, Black 9%, Other 2%. "
                 "Religion: Catholic 50%, Evangelical 31%, None 10%, Spiritist 3%. "
                 "87% urban. Education inequality between cities and rural areas.",
    },
    "Nigeria": {
        "name": "Nigeria",
        "code": "NG",
        "personas": NIGERIA_PERSONAS,
        "notes": "Demographics based on NBS 2023 and Afrobarometer Round 9. "
                 "Religion: Muslim 53%, Christian 46%, Traditional 1%. "
                 "Major ethnic groups: Hausa-Fulani 30%, Yoruba 15%, Igbo 18%, Other 37%. "
                 "Young demographic: median age ~18. Urban: 54%.",
    },
    "Japan": {
        "name": "Japan",
        "code": "JP",
        "personas": JAPAN_PERSONAS,
        "notes": "Demographics based on Statistics Bureau of Japan 2023 and NHK Survey 2023. "
                 "Oldest median age: ~48.6. Religion: largely secular; Buddhist/Shinto syncretic. "
                 "Education: 92% complete high school. Dominant party: LDP. "
                 "Political engagement low: high 'None/Independent' share.",
    },
}


# ---------------------------------------------------------------------------
# Assemble personas with IDs and backward-compatibility aliases
# ---------------------------------------------------------------------------

def build_database():
    all_personas = []

    for country_key, meta in COUNTRY_META.items():
        code = meta["code"].lower()
        for i, p in enumerate(meta["personas"], start=1):
            persona = {
                "id": f"{code}_{i:03d}",
                "country": meta["name"],
                "country_code": meta["code"],
                **p,
                # Backward-compatibility aliases for [RACE] and [PARTY] tags in
                # existing human-ai-eval prompt templates (agent.py format_personalization)
                "race": p["ethnicity"],
                "party": p["political_party"],
            }
            all_personas.append(persona)

    database = {
        "metadata": {
            "description": (
                "Demographically representative persona database for the human-ai-eval framework. "
                "180 personas across 6 countries (30 per country), stratified by age, gender, "
                "education, religion, political orientation, ethnicity, and urban/rural location. "
                "Compatible with format_personalization() [TAG] substitution in simulate/agent.py."
            ),
            "version": "1.0",
            "created": "2026-03-16",
            "total_personas": len(all_personas),
            "countries": list(COUNTRY_META.keys()),
            "personas_per_country": 30,
            "fields": [
                "id", "country", "country_code", "age", "gender", "education",
                "employment_status", "income_level", "urban_rural", "marital_status",
                "religion", "political_orientation", "political_party", "ethnicity",
                "race",   # alias for ethnicity — maps to [RACE] tag in prompt templates
                "party",  # alias for political_party — maps to [PARTY] tag in prompt templates
            ],
            "country_notes": {k: v["notes"] for k, v in COUNTRY_META.items()},
            "sources": [
                "arXiv:2511.21722 — German General Personas (GGP-ALLBUS-2023)",
                "arXiv:2407.17387 — PERSONA Testbed (SynthLabsAI)",
                "arXiv:2602.18462 — Assessing Reliability of Persona-Conditioned LLMs (WVS-based)",
                "arXiv:2510.11131 — SocioBench EMNLP 2025 (ISSP, 30+ countries)",
                "arXiv:2503.16527 — LLM Generated Persona is a Promise with a Catch",
                "US Census Bureau 2023, Pew Research Center 2023",
                "Census of India 2011 (projected), Lokniti-CSDS, ISSP 2022",
                "Statistisches Bundesamt 2023, ALLBUS 2023",
                "IBGE Census 2022, Datafolha 2023",
                "NBS Nigeria 2023, Afrobarometer Round 9",
                "Statistics Bureau of Japan 2023, NHK Survey 2023",
            ],
            "usage": (
                "Load as DataFrame: pd.read_json('personas.json')['personas']. "
                "Filter by country: df[df['country_code'] == 'US']. "
                "Use with Lab.simulate_experiment() — pass as participants parameter. "
                "Compatible tags in prompt templates: [AGE], [GENDER], [EDUCATION], "
                "[PARTY], [RACE], [POLITICAL_ORIENTATION], [COUNTRY], [ETHNICITY], "
                "[RELIGION], [EMPLOYMENT_STATUS], [INCOME_LEVEL], [URBAN_RURAL], "
                "[MARITAL_STATUS], [POLITICAL_PARTY]."
            ),
        },
        "personas": all_personas,
    }

    return database


if __name__ == "__main__":
    db = build_database()
    out_path = os.path.join(os.path.dirname(__file__), "personas.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)
    print(f"Wrote {db['metadata']['total_personas']} personas to {out_path}")
    for country in db["metadata"]["countries"]:
        count = sum(1 for p in db["personas"] if p["country_code"] == country
                    or p["country"] == COUNTRY_META.get(country, {}).get("name", country))
        print(f"  {country}: {count} personas")
